spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: "root"
    password: "12345678"
    #在这里配置你的数据库
    url: jdbc:mysql://localhost:3306/spider?useUnicode=true&characterEncoding=utf-8&useSSL=false
  jpa:
    hibernate:
      ddl-auto: update
    #show-sql: true
server:
  port: 8080